# Generated by Django 3.2.4 on 2021-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.TextField(max_length=50),
        ),
    ]
