# Generated by Django 3.2.4 on 2021-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_proveedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
