# Generated by Django 3.2.4 on 2021-07-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_proveedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
